<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * 
     * This migration fixes the order_number column to support larger numbers
     * generated by the checkout system.
     */
    public function up(): void
    {
        Schema::table('orders', function (Blueprint $table) {
            // Change order_number from integer to bigInteger (unsigned)
            // This allows values up to 18,446,744,073,709,551,615
            $table->unsignedBigInteger('order_number')->change();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('orders', function (Blueprint $table) {
            // Revert back to integer (not recommended as data may be lost)
            $table->integer('order_number')->change();
        });
    }
};

